[    
 "¿Crees en el amor a primera vista, o debería pasar por aquí otra vez?",
 "¿Tienes un mapa? Me perdí en tus ojos.",
 "Si fueras un ladrón, ¡te robarías mis pensamientos!",
 "¿Tienes un nombre o puedo llamarte mía?",
 "¿Crees en el destino? Porque acabo de encontrarme contigo.",
 "¿Estás cansada? Porque llevas todo el día en mis pensamientos.",
 "¿Te lastimaste cuando caíste del cielo?",
 "Si besarte fuera un crimen, ¿serías mi cómplice?",
 "¿Crees en el amor a distancia, o debo acercarme?",
 "¿Tienes un teléfono? Creo que me perdí en tus ojos y necesito un mapa de regreso.",
 "¿Eres Google? Porque tienes todo lo que estoy buscando.",
 "Si besarte fuera un deporte, ¿serías campeona mundial?",
 "¿Eres un ángel? Porque estoy seguro de que acabo de morir y llegar al cielo.",
 "¿Eres wifi? Porque siento una conexión intensa contigo.",
 "¿Crees en el amor a primera vista, o debería caminar por delante de ti otra vez?",
 "Si fueras una fruta, ¡serías una fruta fina!",
 "¿Sabes qué hora es? Creo que es hora de que nos encontremos.",
 "¿Eres una cámara? Porque cada vez que te miro, sonrío.",
 "¿Tienes un mapa? Me perdí en tus ojos.",
 "¿Tienes un nombre o puedo llamarte mía?",
 "Si fueras un ladrón, ¡te robarías mis pensamientos!", 
 "¿Crees en el destino? Porque acabo de encontrarme contigo.",
 "¿Estás cansada? Porque llevas todo el día en mis pensamientos.",
 "¿Te lastimaste cuando caíste del cielo?",
 "Si besarte fuera un crimen, ¿serías mi cómplice?",
 "¿Crees en el amor a distancia, o debo acercarme?",
 "¿Tienes un teléfono? Creo que me perdí en tus ojos y necesito un mapa de regreso.",
 "Me Gustaría Ser Un Gato Para Pasar 7 Vidas A Tu Lado.",
 "La Riqueza Material Es Inútil, Me Siento Rico A Tu Lado, Y Créeme, No Hay Tesoro Que Pueda Comprarlo.",
 "Robar Está Mal Pero Un Beso De Tu Boca Sí Me Lo Robaría.",
 "A Veces Pienso En Nosotros Dos Recorriendo Los Cielos, El Problema Es Que Siempre Debería Ir Encima De Ti Porque Solo Los Ángeles Tienen Alas.",
 "Si Todos Los Cumplidos Que Mereces Fueran Plumas No Necesitarías Alas Para Subir Al Cielo.",
 "En Este Desierto Que A Veces Es La Vida, El Árbol Que Proporciona La Mejor Sombra Eres Tú.",
 "Qué Hermoso Es El Cielo Cuando Está Claro Pero Más Hermoso Es El Amor Cuando Te Tengo A Mi Lado.",
 "¿Qué Tan Avanzada Es La Ciencia? Porque Ahora Los Chocolates Caminan.",
 "En Tu Ausencia Dibujaré Un Sueño Para Que Regreses En El Hermoso Despertar.",
 "Dije Que Nunca Me Enamoraría Pero Luego Te Conocí Y Todo Cambió.",
 "Bonita, Camina Por La Sombra, El Sol Derrite Los Chocolates.",
 "Si En El Último Minuto De Mi Vida Bajara Un Ángel Del Cielo Y Me Diera A Escoger Entre Una Vida Eterna U Otro Minuto Contigo Yo Te Elegiría Porque La Vida Eterna Sin Ti No Existiría.",
 "Si Fuera Un Correo Electrónico Serías Mi Contraseña.",
 "Tus Ojos Son Como Dos Estrellas Que Brillan En Alta Mar, Me Gustaría Ser Un Marinero Para Alcanzarlos.",
 "Si Cada Vez Que Pensara En Ti Saliera Una Estrella El Cielo Estaría Lleno De Ellas.",
 "Me Gustaría Ser Una Almohada Para Que Me Abraces Cada Mañana.",
 "Si Amarte Es Un Crimen Que Me Castigue La Justicia Porque ¡Seguiré Amándote!",
 "Viví Sin Conocerte Y Cuando Te Conocí Entendí Que No Había Vivido.",
 "Cuando Estás En Mis Brazos Es Como Tener El Mundo Entre Ellos.",
 "En El Cielo, Los Rayos Son Destellos Y En La Tierra Tus Ojos Son Los Más Hermosos.",
 "Todas Las Estrellas Que Aparecerán En El Cielo Iluminarán Tu Belleza. El Sol Revelará Tus Ojos Y Nuestro Amor Se Revelará Transparente.",
 "Necesito El Corazón Para Vivir, Pero Te Necesito Más A Ti Porque Tu Lo Haces Latir.",
 "Me Gustaría Compartir Todos Mis Días Contigo.",
 "Eres La Ola Más Alta En El Mar De Mi Pasión.",
 "Te Conocí Y Me Hiciste Creer De Nuevo En El Amor.",
 "Tus Ojos Son Como La Luna Que Me Hipnotiza Y Me Quitan El Sueño.",
 "Cuando Pienso En Ti, Mi Vida Resplandece, Eres Mi Sol En Un Día Nublado.",
 "Despertar A Tu Lado Es Mi Mejor Regalo, Princesa.",
 "Llamaré A La Justicia Para Que Te Lleve Porque Te Has Robado Mi Corazón.",
 "Tus Besos Me Quitan La Sed Porque Son Gotas De Felicidad.",
 "Cuando Estás En Mis Brazos Me Siento Como Flotando En Las Nubes.",
 "Eres Tan Hermosa Como Las Rosas Porque Le Das Color Al Jardín De Mi Corazón.",
 "Si El Sol Y Tus Ojos Tuviesen Una Competencia Para Ver Quien Brilla Más, Sin Duda Tú Serías La Ganadora.",
 "Mi Corazón Late Al Ritmo De Tus Preciosas Caderas.",
 "Eres Mi Calma En Los Días De Tormentas.",
 "Cuando Llegaste A Mi Vida Me Hiciste Creer De Nuevo En El Amor.",
 "Ni Todas Las Joyas Del Mundo Se Comparan Con Lo Valioso Que Es Estar Contigo.",
 "Dime Tu Nombre Para Grabarlo Eternamente En Mi Corazón.",
 "Si Cada Gota De Agua En Tu Cuerpo Es Un Beso, Entonces, Quiero Convertirme En Un Aguacero.",
 "Contigo Tengo A Mi Verdadero Tesoro Porque Vales Oro.",
 "Desde Que Te Vi No Has Dejado De Vivir En Mis Sueños.",
 "Si La Luna Fuera Oscura, Las Estrellas No Brillarían, Si Mi Amor Fuera Una Mentira, Mis Ojos Lo Mostrarían.",
 "La Vida Es Un Juego De Contrarreloj. Todo Va Muy Rápido Hasta Que Apareces Tú Y Detienes El Tiempo.",
 "Cuando Te Conocí Supe Que Tenía Una Razón Para Amar.",
 "Si Un Día Olvido Lo Hermosa Que Eres Solo Ayúdame A Recordarlo Con La Luz De Tu Sonrisa Y El Sabor De Tus Labios.",
 "Mi Vida A Partir De Ahora Depende Exclusivamente De Ti. Eres Esa Persona Especial Que No Puede Ser Reemplazada.",
 "Aunque El Lugar De Los Ángeles Es El Cielo, Si Te Vas, Te Extrañaré Demasiado.",
 "No Hay Necesidad De Ser Pintor Porque Con Solo Mirarte Se Dibujar Una Sonrisa En Mi Cara Triste.",
 "Se Me Cayeron Unos Besos En Tu Blusa, ¿Puedo Buscarlos?",
 "Me Gustaría Ser El Sol Para Darte Calor Todo El Día.",
 "Para Mi Próximo Truco, Necesito Que Me Beses... Y Mágicamente Haré Que Aparezcan Mariposas En Tu Estómago.",
 "¿Quién Fuera Un Taxi Para Llevar Mi Amor A Las Puertas De Tu Corazón?",
 "Si Yo Fuera Juez Te Sentenciaría Conmigo A Cadena Perpetua.",
 "Envidio El Destino De Los Borrachos Al Verte Pasar Te Verán Tres Veces.",
 "No Eres Google Pero Tienes Todo Lo Que Busco.",
 "Adam Y Eva Se Comieron Una Manzana Pero Yo Me Comería Una Frutería Entera Por Ti.",
 "¡Dicen Que El Amor Es Ciego, Pero No Ves Lo Que Hacen Tus Ojos!",
 "Se Me Cayeron Unos Besos En Tu Blusa, ¿Puedo Buscarlos?",
 "Quisiera Ser Un Caramelo Para Derretirme En Tu Boca.",
 "No Soy Agricultor Pero Puedo Plantarte Muchos Besos.",
 "Por Ti Me Convierto En Escultor Para Moldear Tu Hermoso Cuerpo.",
 "Pareces Un Angelito Caído Del Cielo Con Esa Combinación De Belleza Y Dulzura.",
 "¿No Te Cansas De Estar Todo El Día En Mis Pensamientos?",
 "Iluminas Mi Vida Más Que El Sol En Un Día De Verano.",
 "Por Verte Sonreír Yo Me Convierto En El Mejor De Los Payasos.",
 "Si Doy Positivo Para Embriaguez, Échale La Culpa A Tu Sonrisa.",
 "Tus Abrazos Son Mi Fuente De Energía.",
 "Mis Piernas Tiemblan Como Gelatina Cuando Me Miras.",
 "Si Tuvieras Que Pagar Impuestos Por Tu Belleza Estarías Arruinada.",
 "Pienso En Ti Hasta Dormido, Eres La Invasora De Mentes Más Linda Que Haya Conocido.",
 "Eres Mi Tesoro Más Preciado Y Quiero Estar Siempre A Tu Lado.",
 "Te Invito A Una Cita De Tres: Tú, Yo Y Nuestro Amor.",
 "Mi Felicidad Tiene Nombre: Tú.",
 "Si amarte fuera trabajo, no existiría el desempleo.",
 "Cada vez que te veo, entiendo por qué la belleza inspira a los poetas.",
 "Eres la razón por la cual me levanto con una sonrisa cada día.",
 "Tu mirada tiene el poder de dar luz a mis días más oscuros.",
 "¿Crees en el amor a primera vista o tengo que volver a pasar?",
 "Al verte supe que todas mis búsquedas terminaban en ti.",
 "Eres como un sueño del que nunca quiero despertar.",
 "Mi día empieza y termina con el pensamiento de ti.",
 "Contigo aprendí lo hermoso que es vivir enamorado.",
 "Si pudiera darte algo en la vida, te daría la habilidad de verte a través de mis ojos.",
 "Tener tu amor es tener todo lo que siempre he deseado.",
 "Desde que llegaste a mi vida, todos los días son especiales.",
 "¿Cómo fue eso de enamorarme? Ah sí… viéndote sonreír.",
 "Eres mi casualidad favorita y mi destino más deseado.",
 "Si amarte fuera trabajo, no existirían vacaciones para mi corazón.",
 "Eres como un amanecer: irremplazable, hermoso y capaz de iluminar mi día entero con solo aparecer.",
 "¿Crees en el amor a primera vista o tengo que pasar frente a ti otra vez?",
 "Si la belleza fuera tiempo, tú serías la eternidad.",
 "Me gustaría ser astronauta para poder robarte las estrellas y ponerlas en tus ojos.",
 "No necesito el mapa del tesoro porque el verdadero tesoro es estar a tu lado.",
 "Ojalá fueras mi tarea para estar encima de ti toda la noche.",
 "Tus ojos son dos motivos por los cuales perderme no parece tan mala idea después de todo.",
 "Deberías venir con una advertencia: peligrosamente hermosa.",
 "Eres el sueño del que nunca quiero despertar.",
 "Cada vez que veo tus fotos en las redes sociales, me hacen falta emojis para expresar lo mucho que me gustas.",
 "Si esta noche te sueño es porque te extraño. Si mañana despierto feliz, es porque contigo soñé.",
 "Ojalá fuera poeta para describir con palabras lo que siento cuando te veo pero créeme, ni mil poetas juntos podrían capturar tu esencia completamente.",
 "Tienes algo muy valioso: mi atención completa cada vez que hablas o sonríes.",
 "Tus ojos son como dos lunas, y yo siempre quise viajar al espacio.",
 "Si la belleza fuera tiempo, tú serías la eternidad.",
 "Eres el sueño del que nunca quiero despertar.",
 "Tu sonrisa es la poesía que mis labios desearían recitar.",
 "¿Crees en el amor a primera vista o tengo que volver a pasar?",
 "Contigo aprendí que hay miradas que hacen más ruido que un grito.",
 "Si me das una oportunidad, prometo robarte solo besos.",
 "Eres como ese sueño del que no quieres despertar.",
 "Hasta en mi café prefiero tu dulzura.",
 "¿Te dijeron alguna vez que tus ojos tienen el brillo de las estrellas?",
 "En mi cielo personal, tú eres el sol.",
 "Tienes la llave para abrir cada mañana mi felicidad.",
 "A tu lado, todo camino parece corto.",
 "Si amarte fuera trabajo, no existirían días libres para mí.",
 "Eres la casualidad más bonita que llegó a mi vida.",
 "En cada latido de mi corazón, hay una nota musical que compone la más hermosa melodía, una canción dedicada únicamente a ti, reflejo de todo el amor que siento por tu presencia en mi vida.",
 "Como un navegante perdido en medio del océano, así me sentía antes de conocerte; ahora que estás aquí, he encontrado mi faro en la oscuridad, iluminando cada paso hacia el puerto seguro de tu corazón.",
 "Dicen que las estrellas en el cielo guardan los secretos del universo, pero estoy convencido de que ni la más brillante podría revelar la magnitud del amor y admiración que tengo por ti.",
 "Si pudiese pedir un deseo bajo el resplandor del firmamento nocturno, no desearía ni riqueza ni poder; solo pediría más momentos junto a ti, porque en tu compañía encuentro todo lo que alguna vez soñé tener.",
 "Imagino nuestra historia como un libro eterno donde cada día escribimos un nuevo capítulo lleno de aventuras, risas y amor incondicional. A tu lado, cada página es un tesoro más precioso que el anterior.",
 "Si fueras pirata, definitivamente serías el tesoro que buscaría.",
 "¿Eres mag@? Porque cada vez que te veo, todos los demás desaparecen.",
 "Deberías llamarte Google, porque tienes todo lo que estoy buscando.",
 "Si esta fuera una película, serías la mejor parte.",
 "Oye, ¿te dolió? Cuando caíste del cielo al parecer.",
 "Creo que perdí mi número de teléfono. ¿Puedo tener el tuyo?",
 "Eres como mi café: caliente, dulce y me haces querer levantarme por las mañanas.",
 "Si se supone que los besos son conversaciones… Empecemos con nuestro diálogo.",
 "¡Alerta! La policía busca a un/a ladrón/a de corazones y creo que te encontré.",
 "No soy fotógrafo/a pero puedo imaginarnos juntos/as en un futuro brillante.",
 "Tienes algo en tu cara… Ah no, espera, es solo belleza radiante.",
 "¿Crees en amor a primera vista o tengo que pasar de nuevo?",
 "Me gustaría ser astronauta para poder robarte todas las estrellas y ponerlas en tus ojos.",
 "Eres la razón por la cual los hombres siguen creyendo en milagros."
]
